### ISSUE TITLE
Delete event

### ISSUE THREAD

**Issue by haneenmahd** [AmberBuild/amberbuild#2]
For file changes it now only supports `on_modified` event.
We need if the file is changes and created after the process is started.

**Comment by Blobsy** [comment]
Now, it triggers `on_delete` for both Files and Directories. But, the only difference is when the target 🎯 file is deleted the program exits.
In case of directories it never exits

**Comment by haneenmahd** [comment]
> Now, it triggers `on_delete` for both Files and Directories. But, the only difference is when the target 🎯 file is deleted the program exits.
> In case of directories it never exits

Yes, it does exits.
If it never exits it might go like a infinte loop ♾️ until it finds the file and result in too many crashes and bugs
