### ISSUE TITLE
Have custom condition

### ISSUE THREAD

**Issue by Blobsy** [AmberBuild/amberbuild#8]
**Is your feature request related to a problem? Please describe.**
Yes, I cannot create custom conditions for watching the file 🗃️,.Just specify the count.

**Describe the solution you'd like**
Amber build has a feature to loop until a condition.But, that condition only takes a specific count to loop till

**Describe alternatives you've considered**

**Additional context**

**Comment by haneenmahd** [comment]
Did you mean to use it like this:
```python
from amberbuild import FileWatcher

for i in range(0, 10):
   watcher = FileWatcher("yourfile.ext")
    
   watcher.watch(i)
```
This is gonna result in so many errors ❌ .
First the watcher runs from 0...1 and from 0...2 and 0...3 and till it reaches 0...10.
This may go like a infinite loop ➿ and soon 🔜 resulting in crashing.
